### ISSUE TITLE
filter เป็นสถานะ ทั้งหมด ไม่โชว์ข้อมูลทั้งหมด

### ISSUE THREAD

**Issue by Natkun** [mmismahidol/purchasing-frontend#54]
กรณี filter เป็นสถานะอื่นๆ เช่น เตรียมหรืออนุมัติ พอเปลี่ยนกลับมาเป็นทั้งหมด -> รายการที่แสดงไม่กลับมาทั้งหมด จะค้างเป็นรายการของสถานะนั้นๆแทน
![image](https://user-images.githubusercontent.com/20655314/33196417-93db5678-d111-11e7-8b58-c75952f67d6e.png)

**Comment by dixonsatit** [comment]
ปรับให้แล้วนะครับ
