### ISSUE TITLE
กรณีสร้างใบสั่งซื้อใหม่ ซึ่งมี 1 รายการที่ไม่มีราคาต่อหน่วย เป็นการใส่เอง 

### ISSUE THREAD

**Issue by Natkun** [mmismahidol/purchasing-frontend#55]
![image](https://user-images.githubusercontent.com/20655314/33196433-aaa0b1f0-d111-11e7-9fb7-c15630a60718.png)
-> หลังจากกดไปแก้ไข รายการที่ไม่มีราคาต่อหน่วย ช่องราคา ค่าจะหายไป (ไม่แน่ใจว่าหรือจะต้องกำหนดราคาต่อหน่วยก่อนรึเปล่าคะ)
![image](https://user-images.githubusercontent.com/20655314/33196437-b185124a-d111-11e7-8fd5-b0e4a2ce39ee.png)

**Comment by dixonsatit** [comment]
ปกติมันจะมีราคาให้นะครับ ถ้าไม่มีก็กรอกเข้าไปเองได้ครับ
