### ISSUE TITLE
กรณี แก้ไขใบสั่งซื้อ ลบรายการไม่ได้

### ISSUE THREAD

**Issue by Natkun** [mmismahidol/purchasing-frontend#56]
![image](https://user-images.githubusercontent.com/20655314/33197766-f9552436-d119-11e7-8b8c-2bd56e28144f.png)
กดลบไปแล้ว ยอดยังไม่ลด
![image](https://user-images.githubusercontent.com/20655314/33197776-056585ae-d11a-11e7-8ffa-c97f51234f73.png)
หลังจาก กดบันทึก มากดดูอีกครั้ง รายการยังเหมือนเดิม
![image](https://user-images.githubusercontent.com/20655314/33197790-17d302a2-d11a-11e7-85f3-7f6d4ff5541d.png)

**Comment by dixonsatit** [comment]
แก้ไขให้เรียบร้อยครับ
