### ISSUE TITLE
กรณี filter สถานะ ยืนยัน ยังไม่กรองรายการ

### ISSUE THREAD

**Issue by Natkun** [mmismahidol/purchasing-frontend#58]
![image](https://user-images.githubusercontent.com/20655314/33197887-8f639642-d11a-11e7-8454-89ce879ad968.png)

**Comment by dixonsatit** [comment]
หรับปรุงให้แล้วนะครับ b427ba61dc9a63676ea0e8d0a77c5d5021fb18f7
